version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    working_directory: ~/repo

    steps:
      - run: apt-get update && apt-get install -y build-essential git ssh
      - checkout
      - run: make -j
